spring:
    application:
        name: auth-service
    datasource:
      password: iiitn123
      url: jdbc:mysql://localhost:3306/user_details
      username: root
    jpa:
      hibernate:
        ddl-auto: none

    flyway:
      enabled: true
      locations: classpath:db/bootstrap
      baseline-on-migrate: true
      validate-migration-naming: true
server:
  port: 8081

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org:
      springframework: debug

#jwt values
security:
  jwt:
    secret-key: 036e0ce585032470454dc6ece4e78ac74918d56b70774ae7d1fd45ca0725ac4a
    expiration-time: 36000000
